/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:3b27a08d-96d7-486c-9a3c-e62cce8aeeb2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_4ASBtHNIH",
    "aws_user_pools_web_client_id": "7ftuuc0cpb1a9bfp6sla5hgfsq",
    "oauth": {},
    "aws_user_files_s3_bucket": "mybookstore1f6a66e75bcb406cb48c38d8f9474ffc121737-prod",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://nlgvklrfbja2hazfd6kcmokawe.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-rqrtbkzt6jhm3mdbpseabfscdq"
};


export default awsmobile;
